name: $(majorVersion).$(minorVersion).$(rev:r)

variables:
  majorVersion: "0"
  minorVersion: "1"

trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - "shared-infrastructure/*"

pr: none

pool:
  name: "Continuous Integration 02 - SSD - 160ACU"

steps:
  - task: CopyFiles@2
    displayName: "Copy Files to: $(build.artifactstagingdirectory)"
    inputs:
      Contents: |
        shared-infrastructure\**\*.json
      TargetFolder: "$(build.artifactstagingdirectory)"
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)"
